apiVersion: v1
kind: Secret
metadata:
  name: secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  # klucz dla frontendu
  secret_key: {{ .Values.frontend.secretKey | default "changeme" | b64enc }}
  # klucz dla backendu (np. JWT)
  jwt_key: {{ .Values.backend.jwt.secret | default "changeme" | b64enc }}
