nameOverride: ""
fullnameOverride: ""
podAnnotations: { }
podLabels: { }

backend:
  replicaCount: 1

  image:
    repository: "ghcr.io/dawid-walkiewicz/wuda-backend"
    pullPolicy: IfNotPresent
    tag: "latest"

  nameOverride: ""
  fullnameOverride: ""

  service:
    type: ClusterIP
    port: 5000

  # optional db configuration if postgresql is not enabled
  database:
    host: ""
    port: ""
    name: ""

    # user and password
    existingSecret: ""

  jwt:
    existingSecret: "secrets"

  livenessProbe:
    initialDelaySeconds: 15
    timeoutSeconds: 10

  readinessProbe:
    initialDelaySeconds: 60
    timeoutSeconds: 15

frontend:
  replicaCount: 1

  image:
    repository: "ghcr.io/dawid-walkiewicz/wuda-frontend"
    pullPolicy: IfNotPresent
    tag: "latest"

  nameOverride: ""
  fullnameOverride: ""

  service:
    type: NodePort
    port: 8000

  # secret_key for frontend
  existingSecret: "secrets"

postgresql:
  enabled: true
  auth:
    database: "games"
    username: "board_games"
  primary:
    persistence:
      enabled: true
      size: 4Gi
    pdb:
      create: false

ingress:
  enabled: false
  className: "nginx"
  annotations:
   kubernetes.io/ingress.class: nginx
   #kubernetes.io/tls-acme: "true"
  hosts:
    - host: wuda.local
      paths:
        - path: /
          pathType: Prefix

  tls:
  #  - secretName: chart-example-tls
      #- hosts:
       # - wuda.local

httpRoute:
  enabled: true
  annotations: { }
  parentRefs:
    - name: wuda-ext
      namespace: gateway-api
      sectionName: https
  hostnames:
    - dawmat.vizards.it
  rules:
#    - matches:
#        - path:
#            type: PathPrefix
#            value: /headers
  #   filters:
  #   - type: RequestHeaderModifier
  #     requestHeaderModifier:
  #       set:
  #       - name: My-Overwrite-Header
  #         value: this-is-the-only-value
  #       remove:
  #       - User-Agent
  # - matches:
  #   - path:
  #       type: PathPrefix
  #       value: /echo
  #     headers:
  #     - name: version
  #       value: v2
