apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wuda-app.fullnameBackend" . }}
  labels:
    {{- include "wuda-app.labelsBackend" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      {{- include "wuda-app.selectorLabelsBackend" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{ include "wuda-app.labelsBackend" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.service.port }}
              protocol: TCP
          env:
            - name: DB_HOST
              value: {{ .Values.backend.config.DB_HOST | default (printf "%s-postgresql" .Release.Name) | quote }}
            - name: DB_PORT
              value: {{ .Values.backend.config.DB_PORT | quote }}
            - name: DB_DATABASE
              value: {{ .Values.backend.config.DB_DATABASE | default .Values.postgresql.global.postgresql.auth.database | quote }}
            - name: DB_USERNAME
              value: {{ .Values.backend.config.DB_USERNAME | default .Values.postgresql.global.postgresql.auth.username | quote }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-postgresql" .Release.Name }}
                  key: postgresql-password
          livenessProbe:
            httpGet:
              path: /liveness
              port: {{ .Values.backend.service.port }}
            initialDelaySeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /readiness
              port: {{ .Values.backend.service.port }}
            initialDelaySeconds: 20
            timeoutSeconds: 5