apiVersion: v1
kind: Service
metadata:
  name: {{ include "wuda-app.fullnameBackend" . }}
  labels:
    {{ include "wuda-app.labelsBackend" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.port }}
  selector:
    {{ include "wuda-app.selectorLabelsBackend" . | nindent 4 }}
