apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wuda-app.fullnameBackend" . }}
  labels:
    {{- include "wuda-app.labelsBackend" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      {{- include "wuda-app.selectorLabelsBackend" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{ include "wuda-app.labelsBackend" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.service.port }}
              protocol: TCP
          env:
            {{- if .Values.postgresql.enabled }}
            - name: POSTGRES_HOST
              value: {{ printf "%s-postgresql" .Release.Name | quote }}
            - name: PORT
              value: {{ .Values.postgresql.primary.service.ports.postgresql | default "5432" | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.auth.database | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.auth.username | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-postgresql" .Release.Name }}
                  key: password
            {{- else }}
            - name: POSTGRES_HOST
              value: {{ .Values.backend.database.host | quote }}
            - name: PORT
              value: {{ .Values.backend.database.port | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.backend.database.name | quote }}
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.backend.database.existingSecret }}
                  key: user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.backend.database.existingSecret }}
                  key: password
            {{- end}}
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.backend.jwt.existingSecret }}
                  key: jwt_key
          livenessProbe:
            httpGet:
              path: /liveness
              port: {{ .Values.backend.service.port }}
            initialDelaySeconds: {{ .Values.backend.livenessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.backend.livenessProbe.timeoutSeconds }}
          readinessProbe:
            httpGet:
              path: /readiness
              port: {{ .Values.backend.service.port }}
            initialDelaySeconds: {{ .Values.backend.readinessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.backend.readinessProbe.timeoutSeconds }}